name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "6c7da1d2-f07f-4b9a-9e8a-d80a14fdc338"
